#!/usr/bin/expect
        set     timeout   10
        set     RBakdir   "/data/rsvn_backup"
        set     Host    "X.X.X.X"
        set     BakDir  "/data/svn_backup"
        set     Time    "`date '+%F-%H-%M-%S'`"
        set     Password        "XXXXXXXXX"
        set     port    "41000"
        spawn scp -P $port 123.txt root@${Host}:${RBakdir}
        expect  {
		"yes/no" { send "yes\r"; exp_continue}
        	"password:"  { send "$Password\r"}
		}       
        expect  eof
        

